### ISSUE TITLE
Flowchart draft + question

### ISSUE THREAD

**Issue by Hodge-zf** [KenanJones/automobile#2]
Hey @KenanJones  I sent this as an email but this is probably a better place to post it & discuss:

I just started cookie-cutting flowcharts. Here's the link to my first one:

https://www.lucidchart.com/invitations/accept/91f0efaa-2b44-4cb9-bfb2-608c31b44aa6

I wasn't sure how we handled some of the options. For example, there are options to upgrade the brakes to a "High Performance" version. Would the proper syntax be 

"Add Optional Brakes" -> "High Performance Brake Pads"

or 

"Add High Performance Brake Pads" -> "Yes"

and should it include a "Stay with default/No" choice?

**Comment by KenanJones** [comment]
perhaps "Select Brakes" -> "High Performance Brake Pads"
