### ISSUE TITLE
parts needed

### ISSUE THREAD

**Issue by KenanJones** [KenanJones/automobile#3]
@evanrivera @Hodge-zf
please try to find all the parts you need that are not already made so that I can write those classes before we start coding the builders. examples might be fancy wheels or tires, special brakes, engines with VVT, etc.

**Comment by KenanJones** [comment]
@anthonykulis
when I extend the parts we need, where should I put them? mabye edu/jalc/automobile/onlinebuilder/builders/dodgeram/challenger/parts/apropriatedirectory?

**Comment by anthonykulis** [comment]
under your model of vehicle. so something like

`automobile/edu/jalc/automobile/onlinebuilder/builders/dodgeram/challenger/parts`

Of course make sure to group them logically in sub directories

**Comment by KenanJones** [comment]
All parts completed . . . I think :)
