### ISSUE TITLE
Challenger 392 HEMI SCAT PACK SHAKER

### ISSUE THREAD

**Issue by KenanJones** [KenanJones/automobile#7]
@hodge-zf @evanrivera
I will take the 392 HEMI SCAT PACK SHAKER for the extra credit if you don't mind. I don't think either of you have started it yet. Let me know if you want me to choose a different one. Thanks!

**Comment by Hodge-zf** [comment]
I was JUST about to start on it haha. I'll skip to the T/A 392, which should be my last one.

**Comment by KenanJones** [comment]
![image](https://cloud.githubusercontent.com/assets/25179640/25013892/1395a61c-203b-11e7-9885-4b517937b1c8.png)

**Comment by KenanJones** [comment]
![image](https://cloud.githubusercontent.com/assets/25179640/25014705/7557d656-203e-11e7-91b0-087bac32fdf1.png)

**Comment by KenanJones** [comment]
moved to pull request.
